const name = 'ami';

try {
    name = 'tumi';
}
// catch inside error / ex  these are written
catch (error) {
    console.log(error);

}

console.log(name);